### ISSUE TITLE
报 [ERROR] cURL error 77: error setting certificate file: /etc/ssl/certs/ca-certificates.crt 

### ISSUE THREAD

**Issue by 1107012776** [hyperf/box#13]
[root@masterk8s seata-php]# box get php@8.1
[ERROR] cURL error 77: error setting certificate file: /etc/ssl/certs/ca-certificates.crt (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.github.com/repos/dixyes/lwmbs/actions/runs/2594401174/artifacts
Call to a member function getRealPath() on null
不知道这个怎么处理

**Comment by 1107012776** [comment]
Centos 7.5

**Comment by huangzhhui** [comment]
检查下你的网络情况，确认能否连通 Github，因为目前资源都是从 Github 上去下载的

**Comment by 1107012776** [comment]
证书名字不一样导致的，已经解决了
[root@masterk8s ~]# cd /etc/ssl/certs
[root@masterk8s certs]# ls
ca-bundle.crt  ca-bundle.trust.crt    make-dummy-cert  Makefile  renew-dummy-cert
[root@masterk8s certs]#cp ca-bundle.crt ca-certificates.crt
