### ISSUE TITLE
mac m1环境下无法打包

### ISSUE THREAD

**Issue by yswx2022** [hyperf/box#58]
ealPath" to "getPathname".
[INFO] Adding main file "bin/hyperf.php"
[INFO] Setting stub
[INFO] Setting default stub bin/hyperf.php.
[INFO] Overwriting existing file box-build.phar.tmp (42464 KiB)
[INFO] 
[INFO]     OK - Creating box-build.phar.tmp (42464 KiB) completed after 46.1s
cat: ./src/box-build.phar.tmp: No such file or directory

                                                                                                       
 [ERROR] The application ./hyperf is built failed. 

提示这个cat: ./src/box-build.phar.tmp: No such file or directory找不到

**Comment by huangzhhui** [comment]
你是要 build-self 吗？

**Comment by huangzhhui** [comment]
你的执行命令和所在文件夹位置是？
