### ISSUE TITLE
window环境启动hyperf项目报错

### ISSUE THREAD

**Issue by asdlin** [hyperf/box#60]
box版本v0.5.2 window环境在hyperf入口修改了hander为ProcScanHandler()
![image](https://user-images.githubusercontent.com/25758236/195497767-15f1a423-ad17-4668-a0e0-80f19c890000.png)
启动的时候提示
Fatal error: Declaration of Hyperf\Engine\Http\Server::bind(string $name, int $port = 0, int $flags = Swow\Socket::BIND_FLAG_NONE) must be compatible with Swow\Socket::bind(string $name, int $port = 0, int $flags = Swow\Socket::BIND_FLAG_NONE): Hyperf\Di\ClassLoader in D:\project\swow-skeleton\vendor\hyperf\engine-swow\src\Http\Server.php on line 53
![image](https://user-images.githubusercontent.com/25758236/195497432-d8628e15-4b17-4bee-99da-34883254f524.png)

**Comment by huangzhhui** [comment]
你创建的 swow-skeleton 并不是 Hyperf 3.0 的，而是面向 2.2 的，你可以通过 `box composer create-project hyperf/swow-skeleton:dev-master` 可以创建对应 3.0 的骨架
