### ISSUE TITLE
怎么装扩展呢？

### ISSUE THREAD

**Issue by he426100** [hyperf/box#67]
比如gd

**Comment by huangzhhui** [comment]
暂不支持

**Comment by wo642436249** [comment]
> 暂不支持

既然开始是玩玩，干脆一次性把所有扩展加进来得了

**Comment by huangzhhui** [comment]
> > 暂不支持
> 
> 
> 
> 既然开始是玩玩，干脆一次性把所有扩展加进来得了

有些扩展是不运行加的，比如 gd 就是，作为一个开源项目，我们也需要遵守对方的开源协议，也需要保护通过 box 打包出来的应用遵循对方的开源协议

**Comment by twose** [comment]
> > 暂不支持
> 
> 既然开始是玩玩，干脆一次性把所有扩展加进来得了


目前已经是尽可能支持所有扩展了，剩下没支持的扩展要么是采用的开源协议禁止了这么做，要么是支持的工作量比较大。
开源团队选择不做一件事情，一定不是毫无缘由的，不要总是想当然…

**Comment by wo642436249** [comment]
> > > 暂不支持
> > 
> > 
> > 既然开始是玩玩，干脆一次性把所有扩展加进来得了
> 
> 目前已经是尽可能支持所有扩展了，剩下没支持的扩展要么是采用的开源协议禁止了这么做，要么是支持的工作量比较大。 开源团队选择不做一件事情，一定不是毫无缘由的，不要总是想当然…

那就不开源，放到网盘里，哈哈
