### ISSUE TITLE
能否去除必须要加到bin目录（环境变量）的限制，像swoole-cli工具包一样随处执行？

### ISSUE THREAD

**Issue by kcloze** [hyperf/box#78]
不加入path，执行报错，出现包没加载

`./box  K��?	�fp��f��fp�Uf��f~�	�H��H�XP���~0������� rD��������7wH���H��r)��0t!�c���1�� wV��H�>H��sDA���4Q��D9��-����������tց�t����tā�t�A��A���J���Iʉ���Lc�H���B�4VH�E�H����)�Hc�H�H��?�� JH� IH����L�H�����<���D0��]����PE����M�x8A����I�@PA�D�m�H�M�H�	H9���	H�pI�pP���}��E����<�� u����H�pI�pP�@��?	����u$�� ���p��?��	��x��?	�H�����uI�����Pfn�f�ߍ�f81�fo�fr�fr� f~�	�f:�	��x��?	�H�����uR�����P��?����pfn�f����f81�fo�fr�fr� f~�	�f:�	��x��?	�H���Ffn@f�(����f81�f8@'�����P��?	�fp��f��fp�Uf��f~�	�H��I�@PH��M��H�]H���E��E1���lI�D$PH;��M��r2H�M��	f��t&H�U�H;w	H�U Fatal error: Uncaught Error: Class "Hyperf\Di\ClassLoader" not found in phar:///Users/leepei/Downloads/box/bin/hyperf.php:45 Stack trace: #0 phar:///Users/leepei/Downloads/box/bin/hyperf.php(51): {closure}() #1 /Users/leepei/Downloads/box(10): include('phar:///Users/l...') #2 {main} thrown in phar:///Users/leepei/Downloads/box/bin/hyperf.php on line 45`

swoole-cli可以随处执行，不报错
![WechatIMG89](https://user-images.githubusercontent.com/1489176/222656985-40b1d159-86fc-40b7-8618-b8d2f8c87432.jpeg)

**Comment by huangzhhui** [comment]
不需要加入 path 的，你再检查一下两个文件是不是同一个 bin

**Comment by kcloze** [comment]
怀疑操作系统配置问题，mac os 11 升级到 13，问题解决
